### ISSUE TITLE
NPE on startup as `app` is null

### ISSUE THREAD

**Issue by I-Al-Istannen** [parttimenerd/jfrtofp-server#2]
Hey,

when running this project using the CLI (`./gradlew run --args="/home/i_al_istannen/src/discord/DocTor/profile.jfr -p 8080`), the server crashes with a null pointer exception.

The offending line is
https://github.com/parttimenerd/jfrtofp-server/blob/4e3afc51877d3d2477195c087aacc0a5e1baf651/src/main/java/me/bechberger/jfrtofp/server/Main.java#L42

which calls
https://github.com/parttimenerd/jfrtofp-server/blob/4e3afc51877d3d2477195c087aacc0a5e1baf651/src/main/java/me/bechberger/jfrtofp/server/Server.java#L242-L244
which calls
https://github.com/parttimenerd/jfrtofp-server/blob/4e3afc51877d3d2477195c087aacc0a5e1baf651/src/main/java/me/bechberger/jfrtofp/server/Server.java#L126-L128

which is initialized by
https://github.com/parttimenerd/jfrtofp-server/blob/4e3afc51877d3d2477195c087aacc0a5e1baf651/src/main/java/me/bechberger/jfrtofp/server/Main.java#L44

As 42 < 44 (only mathematically!), the app isn't yet initialized and the server dies.

Maybe I was just stupid, but a fresh clone does not work for me.

Have a nice day :lady_beetle:

**Comment by parttimenerd** [comment]
Nice (and correct) reasoning, but using the method `Server.startIfNeededAndGetUrl` would be best. I forgot to change it after updating the server API.

Have a nice night and feel free to add any suggestions :)

**Comment by parttimenerd** [comment]
I'll fix it tomorrow morning, so I can test my change properly.
